
title: Jupyter Book Guide
author: Avery Fernandez
logo: Logo.svg

description: >-
  A guide on how to get jupyter books running and how to use it.

html:
  home_page_in_navbar         : false

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib


repository:
  url: https://github.com/AveryUALibrary/JupyterBooksGuide  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
